matrix:
  include:
  - language: node_js
    node_js:
    - node
    cache:
      directories:
      - frontend/node_modules
    before_script:
    - cd frontend
    - npm install
    before_deploy: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAWPLC2AJP74T6IF5U
      secret_access_key:
        secure: OkQS/OSlZi6hS2BVQuNhqySh11n4HQ9AhAHEeOZIAr10olsmsRPmyxXz0mFENDJHYuPhP0eL43ek72coVf5NeHln45dUH/hAQI6cbkGh13JndyZww2uLUZAf6VQ76+GroznDcApbqj8XbDrIUn0XCM+1+zymb+fBPUbXr4ULFJmwsJs0YGE1BUlL17X/EQtypGZ3OUhTVf3AhCG2k/oJ4/CCRZAprpupf3ZalXgjQrua49+90qCmubQMQC487ZYfXpbMzPv4Bihd2wMiwz46f8SzdYDjQnCqxGRo9Lb2Ywnmt7d/3B003VVG6UGI+3VXk6vrpoBkKVD1qM7glqvoWExwlkMus0DOMY86F8rt9YH8hoBT+9Oc64vJ3UE8ZYTvbffEpK1U7PWo2ltqBCi4k90psUtOV4ZTzI0eltL0JxVCsa7tpAHsW6gDLH30tsEqcJYkXpgEyMhQwW7nh0rh3k6QbIYkCoFB6mA5Tc5EX4XYoFba/Ln2UuL270sN4gjh20gsA/cQgmvRxRYFkiQ76ZpI8bLu+JTHRUagBv1YRX9Yl9EPFwYy8R5B/KqErFYEp9ZoWHkuZ/SQZbwlyQd2xe330Zh4RPTQ9V4m2qzuzG5sdpxzFQUxbmD9ya71OfqvDhfUZVu2uGVlfrPzGzhkeUWGvszLPccGXo4SL6n331U=
      bucket: pulsesurveys
      local-dir: build
      acl: public_read
      skip_cleanup: true
      region: us-east-2
  - language: java
    jdk: openjdk8
    before_script:
    - cd send-emails
  - language: java
    jdk: openjdk8
    before_script:
    - cd get-emails
  - language: java
    jdk: openjdk11
    before_script:
    - cd server

