matrix:
  include:
  - language: node_js
    node_js:
    - node
    cache:
      directories:
      - frontend/node_modules
    before_script:
    - cd frontend
    - npm install
    before_deploy: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
        secure: "j6NEEY0BU4e9nYMYqmRDckgt0aGOB9xmBJvlPgeTj97FHSCxJRv1tTpcEwPoqxX0CASORW9Cru0W27OnPE7hW+AR2szx2YfybAwY0R2A2Y1hBj4g61cAvjr32aLz+SBjDrdhh/3SAHsciXrwNL2EKSLrwl0IDl9UiT59DJTOAcO/j9Tjw71+h6Y2zcdS+iKZ8fzlMBxJkg2MXSV9RCSXbU3nY8UcDyeS/RywNvHfbXcX7x3iK/yU+249/IKP1TeDyucxYbCE0Zvv4TEJi09BNIYBGQXGCp/3+wscT6stbj06lGZ96uLN4vZWx7pDfQEJuqfZ6CxgXSoR2DGBpayffI1LI4lVy9R9vwK3fD6p7JW7brktvqnRTqocSW/o8dz6JKjJPNSTQ8NZxPaIPaNWman+52JcN73sMDiuODlDyGiEtB1VyLhjTAwZIaCaLoL9QFcDqb/RFBE+4/+Khl1wM8yQAd5CGz6yuRz6hjbIwvxN+YbzjaT7qpNW4C2p0pjvOnNEAe7wV1BJVvEAHQge2jKVtz+FIJXOZqXefHLAll2t+1obqIv3MnXXTMOhpvszTFod63SXYbNRcS8nXdRvW4AKIQiEguGD48Qk07DMbvPNhd3KdW+wJ0rQECrR3XK4ZKDTE9ajCC6fM9SL3DIf2SJAfZ7khEdBE9liEbl0ccw="
      bucket: pulsesurveys
      local-dir: build
      acl: public_read
      skip_cleanup: true
      region: us-east-2
  - language: java
    jdk: openjdk11
    before_script:
    - cd send-emails
    before_deploy: ./gradlew assemble
    deploy:
      provider: lambda
      function_name: send-emails
      region: us-east-2
      role: "arn:aws:iam::876089648279:role/service-role/send-emails-role-ewrr3mey"
      runtime: "java11"
      handler_name: "io.micronaut.function.aws.MicronautRequestStreamHandler"
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
        secure: "j6NEEY0BU4e9nYMYqmRDckgt0aGOB9xmBJvlPgeTj97FHSCxJRv1tTpcEwPoqxX0CASORW9Cru0W27OnPE7hW+AR2szx2YfybAwY0R2A2Y1hBj4g61cAvjr32aLz+SBjDrdhh/3SAHsciXrwNL2EKSLrwl0IDl9UiT59DJTOAcO/j9Tjw71+h6Y2zcdS+iKZ8fzlMBxJkg2MXSV9RCSXbU3nY8UcDyeS/RywNvHfbXcX7x3iK/yU+249/IKP1TeDyucxYbCE0Zvv4TEJi09BNIYBGQXGCp/3+wscT6stbj06lGZ96uLN4vZWx7pDfQEJuqfZ6CxgXSoR2DGBpayffI1LI4lVy9R9vwK3fD6p7JW7brktvqnRTqocSW/o8dz6JKjJPNSTQ8NZxPaIPaNWman+52JcN73sMDiuODlDyGiEtB1VyLhjTAwZIaCaLoL9QFcDqb/RFBE+4/+Khl1wM8yQAd5CGz6yuRz6hjbIwvxN+YbzjaT7qpNW4C2p0pjvOnNEAe7wV1BJVvEAHQge2jKVtz+FIJXOZqXefHLAll2t+1obqIv3MnXXTMOhpvszTFod63SXYbNRcS8nXdRvW4AKIQiEguGD48Qk07DMbvPNhd3KdW+wJ0rQECrR3XK4ZKDTE9ajCC6fM9SL3DIf2SJAfZ7khEdBE9liEbl0ccw="
  - language: java
    jdk: openjdk8
    before_script:
    - cd get-users
  - language: java
    jdk: openjdk11
    before_script:
    - cd server

