matrix:
  include:
  - language: node_js
    node_js:
    - node
    cache:
      directories:
      - frontend/node_modules
    before_script:
    - cd frontend
    - npm install
    before_deploy: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
        secure: "UktJehF0BW/sm9mNNWXS1WLK7wEbYx5RF+A4bb1v7OoGCU0NaxFxyGSjl83h16mRZm3+nnheL//gbLvNKfN162BcrhexbcCGJYDBkGiCiWBAezyittnjT53kRzt3HdBX2y6OmH2tlBf9Np3lxqdoaL5if5h9rJNkXXpdpdry5WRvT+lhsDaGrwwxIq8HTEDnc/dP8ACLp/uhI5VEq8pa1rhrrN3MxTaWhAvdJWTcZ49Vh3hWHsep/ZohcMnv/rETBwgaxBuWd3ifmWqFzm+6rgaMx2rjTPLRz13/M0nQKt9jtuNa6gXywI8H6y8KiSdBaIInVCQ9RoXKiHX+51yEdKkN5xSzXi8I+2LzipbJo41ABMFxA8ghkGES66dNLhu0tzm1NEytX9s+C5yjo0YZYV+9jHB7Egnvnc9BiCPOp4w+910rBZpHa31+z9qDrHW4NcsOP/0CYisjmM7eeupFZqhQKD2xGM+wK11bKKKNZ7Ic2RASpTzaQvVOT82fA89Przwm3Vs2RGlGjvxN/hk8BVhUrBRKn1hNZuu42pmIoCcQ4htg5as3095jwSpoXXnIsrI1wWL1dRWGBCXkyVh7iaejRPopYlRPMiJd6G4+VZYrYr2BmYdasnjeUdSGtnAPO3g4DsQUin39KWJEJT6ptmGMPOYXxEK6OW3qRuN3GyY="
      bucket: pulsesurveys
      local-dir: build
      acl: public_read
      skip_cleanup: true
      region: us-east-2
  - language: java
    jdk: openjdk11
    before_script:
    - cd send-emails
    before_deploy: ./gradlew assemble
    deploy:
      provider: lambda
      function_name: send-emails
      region: us-east-1
      role: "arn:aws:iam::876089648279:role/service-role/send-emails-role-ewrr3mey"
      runtime: "java11"
      handler_name: "io.micronaut.function.aws.MicronautRequestStreamHandler"
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
        secure: "UktJehF0BW/sm9mNNWXS1WLK7wEbYx5RF+A4bb1v7OoGCU0NaxFxyGSjl83h16mRZm3+nnheL//gbLvNKfN162BcrhexbcCGJYDBkGiCiWBAezyittnjT53kRzt3HdBX2y6OmH2tlBf9Np3lxqdoaL5if5h9rJNkXXpdpdry5WRvT+lhsDaGrwwxIq8HTEDnc/dP8ACLp/uhI5VEq8pa1rhrrN3MxTaWhAvdJWTcZ49Vh3hWHsep/ZohcMnv/rETBwgaxBuWd3ifmWqFzm+6rgaMx2rjTPLRz13/M0nQKt9jtuNa6gXywI8H6y8KiSdBaIInVCQ9RoXKiHX+51yEdKkN5xSzXi8I+2LzipbJo41ABMFxA8ghkGES66dNLhu0tzm1NEytX9s+C5yjo0YZYV+9jHB7Egnvnc9BiCPOp4w+910rBZpHa31+z9qDrHW4NcsOP/0CYisjmM7eeupFZqhQKD2xGM+wK11bKKKNZ7Ic2RASpTzaQvVOT82fA89Przwm3Vs2RGlGjvxN/hk8BVhUrBRKn1hNZuu42pmIoCcQ4htg5as3095jwSpoXXnIsrI1wWL1dRWGBCXkyVh7iaejRPopYlRPMiJd6G4+VZYrYr2BmYdasnjeUdSGtnAPO3g4DsQUin39KWJEJT6ptmGMPOYXxEK6OW3qRuN3GyY="
  - language: java
    jdk: openjdk8
    before_script:
    - cd get-users
  - language: java
    jdk: openjdk11
    before_script:
    - cd server

