matrix:
  include:
  - language: node_js
    node_js:
    - node
    cache:
      directories:
      - frontend/node_modules
    before_script:
    - cd frontend
    - npm install
    before_deploy: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
        secure: "TwOwQYW0anPJyinfy5w6OYcNoocx3NxAGAN8nmzwOoamzLLNZR7/pYRNivmgiu6oj6HBwEqTq0chfnzJ3PfGfdp8yXh/Ml7aUuLuoHOIAnKAwAD4InQjUZH+7y0VzXIhyxntIq66MUC9Ah17wqSA2pxfFUL6712S8I9UQl4gVtS42KgN/B8ny/njbXn55Rie09xsoTJX7GsSyxiqOOBcTH17Mg0Os07fVbYOB60SfkBMdLPbARZ4gLAFc79PjlkbI5YmLeD4nL6jhjVHXlsyoyZNEgoR9JD8PvVHg+jasTW2fdRUioaM+0SdeHvRv/tzPNQ/zyOnMKNz1BpUfRYuFNJkDhK0xw+WLem8h9PKPXwO7qsb6FGc3MwERQaiKFBI5mhwToUKAfN2OQNMHFeL1Tl43L+YbabCDjIWiOEVdNv0qUomSa9M3iMqfFbExIIyyRGJdIpRfvCSgdvNO4oFz8dsvPHpjmz9WOHjx2NCMi7d2THgraoK3bq/MBOAgKNsPk03eS7telhaFpdBBEdKBbUbCJrDaUsN0kJ6ts3hqPfS6ie3VeoR8BzYYbnr3ElpXV1jJflP6v1ybp9cEoeOzLq5cD0U6EbdYZEm0nejoBD7hh1uPXYKwhiICkJZeaYuFwdl/u9/oJX3BsJM4z+bvSreZBVnIlmY1IB5/reBi6I="
      bucket: pulsesurveys
      local-dir: build
      acl: public_read
      skip_cleanup: true
      region: us-east-2
  - language: java
    jdk: openjdk8
    before_script:
    - cd send-emails
  - language: java
    jdk: openjdk8
    before_script:
    - cd get-users
  - language: java
    jdk: openjdk11
    before_script:
    - cd server

